### ISSUE TITLE
chi_n is not initialized

### ISSUE THREAD

**Issue by FedericoV** [RobertTLange/code-and-blog#2]
Hi Robert:

Thanks for sharing your implementation of CMA-ES.  I found that the "chi_n" parameter is not initialized together with the rest of the parameters here: https://github.com/RobertTLange/code-and-blog/blob/f7b189de2608316c40c3021639eb8d9306596ffa/07_neuroevolution/helpers/es_helpers.py#L51

"chi_n" appears here, for example: 
https://github.com/RobertTLange/code-and-blog/blob/f7b189de2608316c40c3021639eb8d9306596ffa/07_neuroevolution/cma_es_toy.py#L75

From a few other implementations online, I found that it was sometimes heuristically initialized to:

"chi_n": jnp.sqrt(n_dim) * (1.0-1.0/(4.0*n_dim) + 1.0/(21.0*n_dim**2)),

and that this worked pretty well in practice for my problems.

**Comment by RobertTLange** [comment]
Thank you Federico! I think I messed something up when switching from `n` denoting the number of dimensions/parameters to `d`. In the `es_helpers` I am defining `chi_d` and that is what I am using in the blog post.

https://github.com/RobertTLange/code-and-blog/blob/f7b189de2608316c40c3021639eb8d9306596ffa/07_neuroevolution/helpers/es_helpers.py#L38

I seem to have forgotten to change this in the toy examples as well. I just fixed the it and added an Apache license. Thank you for pointing this out!
