### ISSUE TITLE
y_w in CMA-ES

### ISSUE THREAD

**Issue by namheegordonkim** [RobertTLange/code-and-blog#7]
Hi Robert,

Thanks for the super helpful implementation guide for CMA-ES in JAX. I came across an inconsistency in the implementation about the variable `y_w` in your code.

Eq. 45 from Hansen's tutorial looks like this

![image](https://user-images.githubusercontent.com/4412529/152778064-d7b85534-55c0-4216-bd71-71b9398ea522.png)

Eq. 41 defines $\left<y\right>_w$ as follows:

![image](https://user-images.githubusercontent.com/4412529/152778184-81b0eb27-39d6-4736-9577-17bcb537c3c6.png)

which is "step of the distribution mean disregarding step-size σ". The pure-python implementation you link in your tutorial honours Eq. 41.

https://github.com/CyberAgentAILab/cmaes/blob/7508e8a7fea0102932a6d57f4a7be528cce306e4/cmaes/_cma.py#L336

However, it seems that y_w is divided by the step size in your implementation.

![image](https://user-images.githubusercontent.com/4412529/152778850-06ed07ec-8928-4c8f-b1bf-cd2d80a0acec.png)

Am I missing something here? I'm not entirely sure how big of a difference this makes either.

**Comment by namheegordonkim** [comment]
Aha, I misread the notation for $y_{1:\lambda}$. My apologies.

**Comment by RobertTLange** [comment]
No worries and thank you for the kind words and being such an active reader 🤗
